security:
  oauth2:
    client:
      access-token-uri: https://dev-501841.okta.com/oauth2/default/v1/token
      user-authorization-uri: https://dev-501841.okta.com/oauth2/default/v1/authorize
      client-id: 0oabx9e2hzCcqX5MU356
      scope: openid profile email
    resource:
      user-info-uri: https://dev-501841.okta.com/oauth2/default/v1/userinfo
      token-info-uri: https://dev-501841.okta.com/oauth2/default/v1/introspect
      prefer-token-info: false
